# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Stories We Tell Ourselves
author: The Research Software Engineer Community
description: > # this means to ignore newlines until "baseurl:"
    Welcome to the Research Software Engineer’s GitHub Organization! We are an open community
    of developers that would like to cross institutional and geographic boundaries to collaborate
    on tools and research software. This site is a catalog of resources and community projects.

baseurl: "/stories-we-tell-ourselves" # the subpath of your site, e.g. /blog
url: ""
reponame: rseng/stories-we-tell-ourselves

markdown: kramdown
permalink: /:year/:title/
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  stories:
    output: true
    permalink: /:collection/:path
  
# Defaults
defaults:
  - 
    scope:
      path: "_stories"
      type: "stories"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
